<?php
/**
 * @file
 * Provides miscellaneous node types for the Ding! project.
 */

/**
 * Implementation of hook_perm().
 *
 * Since we are limiting the ability to create new nodes to certain users,
 * we need to define what those permissions are here. We also define a permission
 * to allow users to edit the nodes they created.
 */
function ding_content_perm() {
  return array(
    'edit advanced node properties',
  );
}

/**
 * Implementation of hook_menu_alter().
 */
function ding_content_menu_alter(&$items) {
  // These node types are only used ad Flexifield placeholders and are not
  // supposed to be used for creating nodes.
  $items['node/add/flexifield-link']['access callback'] = FALSE;
  $items['node/add/flexifield-text']['access callback'] = FALSE;
  $items['node/add/flexifield-ting-refs']['access callback'] = FALSE;
}

/**
 * Implementation of hook_form_alter().
 */
function ding_content_form_alter(&$form, $form_state, $form_id) {
  // Allow access to certain features that are usually restricted to users with
  // the "administer nodes" permission.
  if (substr($form_id, -10) == '_node_form') {
    if (in_array($form['type']['#value'], array('profile', 'article', 'feature'))) {
      // For these node types, we don't want splittable teasers, so let's
      // disable that.
      unset($form['body_field']['teaser_js']);
      unset($form['body_field']['teaser_include']);
    }

    if (user_access('edit advanced node properties')) {
      if (empty($form['revision_information']['revision']['#access'])) {
        if (!isset($form['revision_information'])) {
          // The following is copied from node_form().
          $form['revision_information'] = array(
            '#type' => 'fieldset',
            '#title' => t('Revision information'),
            '#collapsible' => TRUE,
            // Collapsed by default when "Create new revision" is unchecked
            '#collapsed' => !$node->revision,
            '#weight' => 20,
          );
          $form['revision_information']['revision'] = array(
            '#type' => 'checkbox',
            '#title' => t('Create new revision'),
            '#default_value' => $node->revision,
          );
          $form['revision_information']['log'] = array(
            '#type' => 'textarea',
            '#title' => t('Log message'),
            '#default_value' => (isset($node->log) ? $node->log : ''),
            '#rows' => 2,
            '#description' => t('An explanation of the additions or updates being made to help other authors understand your motivations.'),
          );
        }
        $form['revision_information']['revision']['#access'] = TRUE;

        $form['author']['#access'] = TRUE;
        $form['options']['#access'] = TRUE;
      }
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function ding_content_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Allow users other than those with the "administer nodes" permission to
  // specify a node author other than themselves.
  if ($op == 'presave' && user_access('edit advanced node properties')) {
    // Populate the "authored by" field.
    if ($account = user_load(array('name' => $node->name))) {
      $node->uid = $account->uid;
    }
    else {
      $node->uid = 0;
    }
  }
}

require_once('ding_content.features.inc');

