<?php
/**
 * @file ding_page.module
 * Provides the page node type for the Ding! project.
 */

/**
 * Implementation of hook_form_alter().
 */
function ding_page_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'page_node_form') {
    // Hide the comment settings form and disable comments.
    unset($form['comment_settings']);
    $form['comment'] = array(
      '#type' => 'value',
      '#value' => 0,
    );
  }
}

include_once('ding_page.features.inc');
