<?php
/**
 * @file
 * Displays library nodes on a map.
 *
 * Display additional information on mouse over.
 */

/**
 * Implementation of hook_menu().
 */
function ding_library_map_menu() {
  $items = array();

  $items['admin/settings/ding/library_map'] = array(
    'title' => 'Library map',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_library_map_admin_settings_form'),
    'access arguments' => array('configure libraries'),
    'file' => 'ding_library_map.admin.inc',
  );

  return $items;
}

/**
 * Render the map output.
 */
function ding_library_map_display() {
  $module_path = drupal_get_path('module', 'ding_library_map');
  $map_id = 'library-map';
  drupal_add_css($module_path . '/css/ding_library_map.css');

  drupal_add_js(array('dingLibraryMap' => array(
    'fullDayNames' => array(
      'mon' => t('Monday'),
      'tue' => t('Tuesday'),
      'wed' => t('Wednesday'),
      'thu' => t('Thursday'),
      'fri' => t('Friday'),
      'sat' => t('Saturday'),
      'sun' => t('Sunday'),
    ),
    'shortDayNames' => array(
      'mon' => t('Mon'),
      'tue' => t('Tue'),
      'wed' => t('Wed'),
      'thu' => t('Thu'),
      'fri' => t('Fri'),
      'sat' => t('Sat'),
      'sun' => t('Sun'),
    ),
    'markers' => _ding_library_marker_data(),
    'path' => drupal_get_path('module', 'ding_library_map'),
  )), 'setting');

  drupal_add_js($module_path . '/js/jquery.scrollTo/jquery.scrollTo-min.js');
  drupal_add_js($module_path . '/js/jquery.url/jquery.url.js');
  drupal_add_js($module_path . '/js/ding_library_map.js');

  $map = _ding_library_map_data();

  return '<div class="ding-library-map">' . openlayers_render_map($map, 'ding_library_map') . '</div>';
}

/**
 * Helper function to generate map data.
 */
function _ding_library_map_data() {
  $preset = openlayers_preset_load('ding_library_map');
  $map = $preset->data;

  if ($map) {
    $map += array('id' => 'library-map', 'type' => 'map', 'zoom' => 12, 'minzoom' => 9, 'maxzoom' => 14, 'height' => '200px', 'width' => '100%', 'controltype' => 'Small', 'behavior' => array('extramarkerevents' => 1, 'nomousezoom' => 1));
    if ($center = variable_get('ding_library_map_center', false)) {
      if (isset($center['lat']) && isset($center['lon'])
          && $center['lat'] && $center['lon']) {
        $map['center']['initial']['centerpoint'] = $center['lon'] . ', ' . $center['lat'];
      }
    }
  }

  return $map;
}

/**
 * Helper function to generate marker data.
 */
function _ding_library_marker_data() {
  $query = db_query("
    SELECT n.nid, n.title, l.street, l.city, l.postal_code, l.latitude, l.longitude
    FROM location AS l
    LEFT JOIN location_instance AS li ON (l.lid = li.lid)
    LEFT JOIN node AS n ON (li.vid = n.vid)
    LEFT JOIN ding_library dl ON (n.vid = dl.vid)
    WHERE (n.status <> 0) AND (n.type = 'library') AND
          (dl.library_show_on_map = 1);
  ");

	$libraries = array();
	while ($row = db_fetch_object($query)) {
		$libraries[$row->nid] = $row;
  }

  // Load office hours data for each library.
  $oh_data = office_hours_bulk_load(implode(',', array_keys($libraries)), 'field_opening_hours');

  // Add marker for each library.
  $markers = array();
  foreach ($libraries as $lib) {
    $markers['library-' . $lib->nid] = array(
      'nid' => (integer) $lib->nid,
      'latitude' => (float) $lib->latitude,
      'longitude' => (float) $lib->longitude,
      'name' => $lib->title,
      'street' => $lib->street,
      'city' => $lib->city,
      'postal-code' => (integer) $lib->postal_code,
      'opening_hours' => $oh_data['data'][$lib->nid]['week'],
      'url' => url('node/' . $lib->nid, array('absolute' => TRUE)),
      'text' => FALSE
    );
  }

  return $markers;
}

include_once('ding_library_map.features.inc');

