<?php
/**
 * @file
 * Provides the staff profile node type for the Ding! project.
 */

/**
 * Implements hook_nodeapi().
 */
function ding_staff_profile_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'view' && $node->type == 'profile' && $_GET['q'] == 'node/' . $node->nid) {
    return drupal_goto('user/' . $node->uid, NULL, NULL, 301);
  }
}

require_once 'ding_staff_profile.features.inc';
