<?php
// $Id$

// Default interest period is ~six months.
// TODO: move to ding_reservation
define('DING_LIBRARY_USER_DEFAULT_INTEREST_PERIOD', 183);

/**
 * Implementation of hook_menu().
 */
function ding_library_user_menu() {
  $items = array();

  $items['admin/settings/ding_library_user'] = array(
    'title' => 'User settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_library_user_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'ding_library_user.admin.inc',
  );

  $items['user/%user/authenticate'] = array(
    'title' => 'Please authenticate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_library_user_forms_authenticate', 1),
    'access callback' => 'ding_library_user_forms_access',
    'access arguments' => array('ding_library_authenticate', 1),
    'type' => MENU_CALLBACK,
    'file' => 'ding_library_user.forms.inc',
  );

  $items['user/%user/change_pin'] = array(
    'title' => 'Change pin code',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_library_user_forms_change_password', 1),
    'access callback' => 'ding_library_user_forms_access',
    'access arguments' => array('change_pin', 1),
    'type' => MENU_CALLBACK,
    'file' => 'ding_library_user.forms.inc',
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function ding_library_user_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    return array(
      'account' => array(
        'info' => t('Library account/login'),
        'cache' => BLOCK_NO_CACHE,
        'status' => 1,
        'region' => 'account',
      ),
    );
  }
  elseif ($op == 'view' && $delta == 'account') {
    global $user;
    $block = array();

    // If user is not logged in, display the login form.
    if (!$user->uid) {
      jquery_ui_add('ui.dialog');
      jquery_ui_theme_load();
      drupal_add_js(drupal_get_path('module', 'ding_library_user') . '/ding_library_user.login.js');
      $block['content'] = drupal_get_form('user_login_block');
    }
    else {
      $status = ding_library_user_get_status($GLOBALS['user'], FALSE);
      $block['content'] = theme('ding_library_user_status_block', $status);
    }

    return $block;
  }
}

/**
 * Implementation of hook_user().
 */
function ding_library_user_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      if ($account->uid) {
        // Attach the Alma user id and name to the user object when it
        // is loaded, so it's available everywhere the user is.
        // TODO: Remove this, provider handles linking up with backend.
        $data = db_fetch_array(db_query("SELECT * FROM {ding_library_user} WHERE uid = %d LIMIT 1;", $account->uid));
        $account->library_user_id = $data['library_user_id'];
      }
      break;
    case 'delete':
      db_query('DELETE FROM {ding_library_user} WHERE uid=%d', $account->uid);
      break;
  }
}

/**
 * Implementation of hook_init().
 *
 * @todo
 *   Remove when ding_library_user_user is removed.
 */
function ding_library_user_init() {
  global $user;
  $edit = array();

  // Fire our own hook_user to have the Alma data available on the
  // global $user object.
  if ($user->uid > 1) {
    ding_library_user_user('load', $edit, $user);
  }
}

/**
 * Implementation of hook_theme().
 */
function ding_library_user_theme($existing, $type, $theme, $path) {
  return array(
    'ding_library_user_status_block' => array(
      'arguments' => array(
        'user_status' => NULL,
      ),
      'template' => 'ding_library_user_status_block',
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_personal_info' => array(
      'arguments' => array(
        'account' => NULL,
        'library_user_data' => NULL,
      ),
      'template' => 'ding_library_user_personal_info',
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_record_list' => array(
      'arguments' => array(
        'provider_type' => NULL,
        'records' => array(),
      ),
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_forms_loan_details' => array(
      'arguments' => array('form' => NULL),
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_forms_debts_details' => array(
      'arguments' => array('form' => NULL),
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_list_item' => array(
      'arguments' => array('provider_type' => NULL, 'item' => NULL),
      'template' => 'ding-library-user-list-item',
      'file' => 'ding_library_user.theme.inc',
    ),
    'ding_library_user_list_item_image' => array(
      'arguments' => array('provider_type', 'item' => NULL, $preset = NULL),
      'file' => 'ding_library_user.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_library_user_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * Tells CTools (and thus Panels) where to look for plugin code.
 */
function ding_library_user_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Alter the login form to disable the standard Drupal username/password
 * combination and provide our own fields instead.
 */
function ding_library_user_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // Add our own validation and submit handlers.
      $form['#submit'][] = 'ding_library_user_login_submit';

      // Remove the standard user login links.
      unset($form['links']);
      break;
    case 'user_profile_form':
      $account = $form['_account']['#value'];
      // When we have credentials available, make library patron
      // information available for altering.
      $user_info = ding_provider_invoke('user', 'get info', $account);
      if ($user_info != DING_PROVIDER_AUTH_REQUIRED) {
        // Store the patron information for validation purposes.
        $form['ding_library_user_info'] = array(
          '#type' => 'value',
          '#value' => $user_info,
        );

        // Copy the standard mail field, hide it and use the new
        // alma_mail field to edit the e-mail-address registered in Alma.
        $form['account']['ding_library_user_mail'] = $form['account']['mail'];
        $form['account']['mail']['#type'] = 'value';

        // Use the e-mail-address from Alma as the default value for our
        // new e-mail-address field.
        if (isset($user_info['mails'][0])) {
          $form['account']['ding_library_user_mail']['#default_value'] = $user_info['mails'][0]['mail'];
        }

        // Add our own validation and submit handling.
        array_unshift($form['#validate'], 'ding_library_user_profile_validate');

        $form['#submit'][] = 'ding_library_user_profile_submit';

      }
      break;
    case 'ding_library_admin_settings_main_form':
      // Since we're adding an option to the form, the placeholder is no
      // longer needed.
      unset($form['placeholder']);

      $form['ding_library_user_cancel_fetchable_reservable'] = array(
        '#type' => 'checkbox',
        '#title' => t('Allow cancellation of reservations ready for pickup?'),
        '#description' => t('If enabled, this will allow users that have reservations ready for pick-up to cancel those reservations. It does not affect reservations that are not ready for pick-up.'),
        '#default_value' => variable_get('ding_library_user_cancel_fetchable_reservable', TRUE),
      );
      break;
    case 'contact_mail_page':
    	//Alter the name field on contact form to use the display_name value
    	global $user;

    	// Force a user_load hoping that modules will populate the display_name vaue
    	$args = array();
    	user_module_invoke('load', $args, $user);

    	$form['name']["#default_value"] = (isset($user->display_name) && $user->display_name) ? $user->display_name : $user->name;
    	break;
  }
}

/**
 * Validation for the user profile form.
 */
function ding_library_user_profile_validate($form, &$form_state) {
  $user_info = $form_state['values']['ding_library_user_info'];

  // Check if Alma e-mail-address has changed.
  $new_mail = trim($form_state['values']['ding_library_user_mail']);
  if ($new_mail != $user_info['mails'][0]['mail']) {
    if (!filter_var($new_mail, FILTER_VALIDATE_EMAIL)) {
      form_set_error('account][ding_library_user_mail', t('Please enter a valid e-mail-address.'));
    }
    else {
      // Store the new mail as a new value, so we can test for it in the
      // submit handler.
      $form_state['values']['new_mail'] = $new_mail;

      // If no Drupal users has this e-mail-address yet, also update
      // Drupal's records.
      if (!db_result(db_query("SELECT uid FROM {users} WHERE mail = '%s' AND uid != %d;", $form_state['values']['new_mail'], $form['_account']['#value']->uid))) {
        $form_state['values']['mail'] = $new_mail;
      }
    }
  }
}

/**
 * Submit handler for the user profile form.
 */
function ding_library_user_profile_submit($form, &$form_state) {
  $account = $form['_account']['#value'];
  $creds = ding_library_user_get_credentials($account);
  $user_info = $account->ding_library_user_info;
  $new_user_info = array(
    'phones' => $form_state['values']['alma_user_phone'],
    'email' => $form_state['values']['ding_library_user_mail'],
  );
  //TODO figure out how to build new info
  if ($new_user_info != $user_info) {
    module_invoke_all('ding_library_user_update_info', $creds, $new_user_info, $user_info);
  }
}

/**
 * Submit handler for the login form.
 *
 * Redirect user to a configured page on login.
 */
function ding_library_user_login_submit($form, &$form_state) {
  $form_state['redirect'] = variable_get('ding_library_user_login_destination', '<front>');
}

/**
 * Access control for the forms we provide.
 *
 * @param string $name
 *    The form name.
 * @param object $account
 *    The user account.
 * @return boolean
 *    If access was allowed.
 */
function ding_library_user_forms_access($name, $account) {
  switch ($name) {
    case 'ding_library_authenticate':
    case 'change_pin':
    case 'edit_contact_info':
      if ($GLOBALS['user']->uid == $account->uid) {
        return TRUE;
      }
      break;
  }
  return FALSE;
}

/**
 * Get library user status.
 *
 * @param object $account
 *    The user we're getting credentials for.
 * @param boolean $redirect
 *    Whether to redirect and collect credentials from the user if
 *    they're not currently available. Default is TRUE.
 * @return mixed
 *    Returns array of user status if successful, FALSE if not.
 */
function ding_library_user_get_status($account, $redirect=TRUE) {
  static $status;
  if (!isset($status)) {
    $status = array();
  }

  // Return data from static variable cache, if available.
  if (isset($status[$account->uid])) {
    return $status[$account->uid];
  }
  else {
    // Generate the user status by querying the library system for different
    // details. Remember that only non-sensitive information should
    // be available in the status, since that is cached and
    // available without authentication as long as the user's
    // session lasts.
    $data = array();

    $reservations = ding_provider_invoke('reservation', 'list', $account);
    $loans = ding_provider_invoke('loan', 'get loans', $account);
    $data['loan_overdue_count'] = 0;

    if ($loans != DING_PROVIDER_AUTH_REQUIRED) {
      $data['loan_count'] = count($loans);
      foreach ($loans as $loan) {
        if ($loan['due_date'] < date('Y-m-d', $_SERVER['REQUEST_TIME'])) {
          $data['loan_overdue_count']++;
        }
      }
    }

    if ($reservations != DING_PROVIDER_AUTH_REQUIRED) {
      $data['reservation_count'] = count($reservations);
    }

    return $data;
  }
  return FALSE;
}

/**
 * Format an ISO 8601 date using a date format string.
 *
 * @param string $datestring
 *    Date in ISO 8601 format (eg. 2010-04-10).
 * @param string $date_format
 *    The format (in date() style) to use when formatting the date.
 * @return string
 *    Formatted date or original $datestring on failure.
 */
function ding_library_user_format_date($datestring, $date_format) {
  if ($datestring) {
    $timestamp = strtotime($datestring);

    if ($timestamp > 1) {
      return format_date($timestamp, 'custom', $date_format);
    }
  }
  return $datestring;
}

/**
 * Implementation of loan form element.
 *
 * @todo
 *   Is this used anywhere?
 */
function ding_library_user_elements_loan_process($element, $form_state) {
  $element['#prefix'] = '<li class="loan loan-' . $element['#loan']['id'] . '">';
  $element['#suffix'] = '</li>';

  if ($element['#loan']['is_renewable']) {
    $element['selected'] = array(
      '#type' => 'checkbox',
      '#prefix' => '<div class="select">',
      '#suffix' => '</div>',
    );
  }
  else {
    $element['not_renewable'] = array(
      '#value' => t('Not renewable'),
      '#prefix' => '<div class="select">',
      '#suffix' => '</div>',
    );
  }

  $element['title'] = array(
    '#value' => $element['#loan']['id'],
    '#prefix' => '<div class="title">',
    '#suffix' => '</div>',
  );

  return $element;
}
